development:
  adapter: sqlite3
  encoding: unicode
  database: parking_development
  pool: 5
    
test:
  adapter: postgresql
  encoding: unicode
  database: parking_test
  pool: 5
  username:
  password:
